#!/bin/bash

# Make sure the agent is an executable
chmod +x ${OPENSHIFT_REPO_DIR}logentries/le.py

# If the config exists, the agent is registered and following files
if [ ! -f "${OPENSHIFT_DATA_DIR}config" ];
then
	# Load the user config with Logentries Account Key
	source ${OPENSHIFT_REPO_DIR}logentries/le_config.ini

	${OPENSHIFT_REPO_DIR}logentries/le.py register --hostname=${OPENSHIFT_APP_NAME} --account-key=${ACCOUNT_KEY}
fi

# We don't want just OPENSHIFT_LOG_DIR as it could be a duplicate
for dir in `env | grep OPENSHIFT_.*_LOG_DIR`
do
	logdir=${dir#*=}
	for logf in `ls $logdir`
	do
		# Check if its access or error log
		if [[ $logf == *_log-*  || $logf == *.log ]]
		then
			# Navigate to the log directory
			pushd $logdir > /dev/null

			# Get the full filename without timestamp
        	if [[ $logf == *_log-* ]]
            then
                # with date
                # formatted filename example name_log-[date]
			    filename="$logdir${logf%%-*}-*"
			else
					if [[ $logf == *-*.log ]]
					then
					    # with date, ending with .log
					    #formatted filename example  name-[date].log
			    	    filename="$logdir${logf%%-*.log}*.log"
					else
					    # no date.
					    # formatted filename example name.log
						filename="$logdir${logf}"
					fi
			fi

			# Follow any new logs and make sure existing ones are being followed
			${OPENSHIFT_REPO_DIR}logentries/le.py follow "$filename"

			popd > /dev/null
		fi
	done
done

# Start monitoring the log files
${OPENSHIFT_REPO_DIR}logentries/le.py monitordaemon
